# YOLO推理服务器 Docker配置

version: '3.8'

services:
  yolo-inference:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./weights:/app/weights
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./_configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - yolo-inference
    restart: unless-stopped

networks:
  default:
    driver: bridge
