model:
  config_path: yolov5/yolov5s.yaml
  weight_path: weights/yolov5s.ckpt
preprocess:
  input_size: 640
  interpolation: 1
postprocess:
  confidence_threshold: 0.3
  iou_threshold: 0.45
server:
  port: 8000
  host: 0.0.0.0
class_names:
  - person
  - bicycle
  - car
  - motorcycle
  - airplane
  - bus
  - train
  - truck
  - boat
  - traffic light